# Generated by Django 3.0.6 on 2020-06-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200613_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='video_url',
        ),
        migrations.AddField(
            model_name='work',
            name='video_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail_1',
            field=models.ImageField(blank=True, null=True, upload_to='work_detail'),
        ),
    ]
