# Generated by Django 3.0.6 on 2020-06-18 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
